creation_rules:
  - path_regex: '.*\.enc\.yaml$'
    key_groups:
      - age:
          # Workstations
          - "age1uklexwmu0y5kdlly9l33kn9gmvzuh395l0lj9dn943v0m80cd9eqp4vc8w"
          - "age1c504s4cnsefv455h36jfn0q2yev0jy4ca9nwx6yt2mgqgksgm4ls5sqe9z"
