{
  config,
  lib,
  pkgs,
  ...
}:

{
  imports = [
    ./autostart.nix
    ./binds.nix
    ./hyprshot.nix
    ./web-apps.nix
    ./waybar.nix
    ./hypridle.nix
    ./hyprlock.nix
    ./input.nix
    ./permissions.nix
    ./pretty.nix
    ./sunset.nix
    ./windowrules.nix
  ];

  config = {
    features.hyprland.hypridle.enable = lib.mkDefault true;
    features.hyprland.hyprlock.enable = lib.mkDefault true;
    features.hyprland.hyprshot.enable = lib.mkDefault true;

    home.packages = with pkgs; [
      playerctl
      impala
    ];

    wayland.windowManager.hyprland = {
      enable = true;
      configType = "lua";
      settings = {
        config = {
          general = {
            allow_tearing = true;
          };
        };
        env = [
          {
            _args = [
              "GDK_DPI_SCALE"
              (builtins.toString config.features.theming.scaling)
            ];
          }
          {
            _args = [
              "QT_SCALE_FACTOR"
              (builtins.toString config.features.theming.scaling)
            ];
          }
          {
            _args = [
              "QT_FONT_DPI"
              "72"
            ];
          }
        ];
      };
    };

    # Hyprland cannot switch between the legacy and Lua config managers during
    # a reload. Only reload instances that already started with Lua; the first
    # migration therefore takes effect on the next Hyprland session without
    # replacing the current session with the autogenerated fallback config.
    xdg.configFile."hypr/hyprland.lua".onChange = lib.mkForce ''
      runtime_dir="''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

      if [[ -d "$runtime_dir/hypr" ]]; then
        for instance in $(${lib.getExe' pkgs.hyprland "hyprctl"} instances -j | ${lib.getExe pkgs.jq} -r '.[].instance'); do
          log_file="$runtime_dir/hypr/$instance/hyprland.log"

          if ${pkgs.gnugrep}/bin/grep -Fq '[cfg] Config is lua' "$log_file" 2>/dev/null; then
            ${lib.getExe' pkgs.hyprland "hyprctl"} -i "$instance" reload config-only
          fi
        done
      fi
    '';
  };
}
